import { NavBar } from "@/exports";
import type { Metadata } from "next";
import { Prata } from "next/font/google";
import "./globals.css";

const FontPrata = Prata({
  weight: "400",
  style: "normal",
  variable: "--prata",
  subsets: ["latin", "cyrillic", "cyrillic-ext", "vietnamese"],
});

export const metadata: Metadata = {
  title: "Solidariza WebSite",
  description: "Generated by create next app",
};

const RootLayout = ({ children, }: Readonly<{ children: React.ReactNode; }>) => {
  return (
    <html lang="pt-BR">
      <body className={`${FontPrata.variable}`}>
        {children}
        <NavBar />
      </body>
    </html>
  );
};

export default RootLayout;
